### ISSUE TITLE
Unexpected high memory usage of volume drivers after a 12 hour load test

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/volumedriver#220] opened 2017-01-06 12:15 UTC
http://tickets.openvstorage.com/projects/OVSSUP/queues/2/OVSSUP-161

After a 12 hour load test on a moderately loaded environment, volumedriver_fs processes show an unexpected high amount of memory usage.

Load test:
- 14 volumes of 100 GB per volumedriver
- 12 hours of capped fio tests on 2k iops

Top output:
```
27507 root      20   0 46.893g 0.013t  22804 S   2.0  5.2 209:50.80 volumedriver_fs -f --config arakoon://config/ovs/vpools/2c7433a0-1e41-41c6-b162-a1418e86dc53/hosts/vmstor1KFRc9KSszk9hAS9/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Fa+
29748 root      20   0 68.508g 0.018t  21628 S   1.0  7.1   3075:25 volumedriver_fs -f --config arakoon://config/ovs/vpools/c6742430-7654-43c0-ac68-8cce95dd6820/hosts/data021KFRc9KSszk9hAS9/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Fa+
31981 root      20   0 32.182g 0.011t  20720 S   0.3  4.4   1793:21 volumedriver_fs -f --config arakoon://config/ovs/vpools/63a0ee46-d3a4-4cab-ab0f-e2db25f0d506/hosts/data031KFRc9KSszk9hAS9/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Fa+
34142 root      20   0 67.974g 0.020t  21864 S   0.3  8.0   2963:18 volumedriver_fs -f --config arakoon://config/ovs/vpools/dd1a95bf-1f6d-4b93-80ca-50238840ac37/hosts/data011KFRc9KSszk9hAS9/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Fa+
25392 root      20   0 35.280g 0.010t  20948 S   0.0  4.0   2178:18 volumedriver_fs -f --config arakoon://config/ovs/vpools/998a9ca4-0476-4660-8b08-6fdf0a4c339b/hosts/data041KFRc9KSszk9hAS9/config?ini=%2Fopt%2FOpenvStorage%2Fconfig%2Fa+
```

VDisk distribution:
```
       | 10.109.3.45 | 10.109.3.46 | 10.109.3.47 | 10.109.3.48 | totals
-----------------------------------------------------------------------
data01 | 12          | 13          | 13          | 14          | 52
-----------------------------------------------------------------------
data02 | 12          | 15          | 14          | 12          | 53
-----------------------------------------------------------------------
data03 | 13          | 12          | 14          | 14          | 53
-----------------------------------------------------------------------
data04 | 13          | 13          | 14          | 13          | 53
-----------------------------------------------------------------------
vmstor | 114         | 117         | 114         | 117         | 462
-----------------------------------------------------------------------
totals | 164         | 170         | 169         | 170
```

**Comment by wimpers** [comment] 2017-01-09 09:42
I had a talk with @fastgeert and he noticed the high memory usage on voldrvs which had many clones (bootdisks and cloudinit) while the ones with datadisks didn't see the issue.

**Comment by saelbrec** [comment] 2017-01-09 10:55
@pploegaert ,
Is there any integration test that could tell us of this is regression or has always been there?

**Comment by redlicha** [comment] 2017-01-17 09:17
Hypothesis for now: on the same env we observed a case where volumedriver "locked up" in the I/O path: I/O threads were waiting for a lock in `DataStoreNG` with no other thread being identifiable as owning the lock. Indirectly this caused mgmt calls to pile up, which in turn lead to excessive memory consumption.

**Comment by redlicha** [comment] 2017-01-24 08:34
Observed once more, this time the root cause could be identified - https://github.com/openvstorage/alba/issues/587

**Comment by redlicha** [comment] 2017-01-30 21:01
Closing this one: the number of mgmt connections / threads is now limited. The underlying cause(s) should be addressed in distinct tickets.

**Closed by redlicha** 2017-01-30 21:01 UTC
Labels: state_question
