### ISSUE TITLE
During machine migration the statistics_volume call becomes slow

### ISSUE THREAD

**Issue by khenderick** [openvstorage/volumedriver#74] opened 2016-07-26 13:01 UTC
During machine migration the `statistics_volume` call becomes slow (+5 seconds)

```
...
156ab06f-0b0b-41ce-8001-ca683a302939: WIN1-2k8-rou-d1
Object: VDisk('3e7cd5bb-f72b-4163-825d-5da4540a0830')
- info: avg 0.012s (min: 0.012s, max: 0.012s)
- statistics: avg 0.014s (min: 0.014s, max: 0.014s)
- snapshots: avg 0.106s (min: 0.106s, max: 0.106s)
- storagedriver_id: avg 0.000s (min: 0.000s, max: 0.000s)
- storagerouter_guid: avg 0.002s (min: 0.002s, max: 0.002s)
- is_vtemplate: avg 0.000s (min: 0.000s, max: 0.000s)
Took 0.134s for 1 iterations
Avg: 0.134s, min: 0.134s, max: 0.134s
6f950bbd-3316-4a99-b5bf-00eec09b6fb9: test3
Object: VDisk('46cfbbf4-d8c2-4431-a105-9b547af6ff1f')
- info: avg 0.038s (min: 0.038s, max: 0.038s)
- statistics: avg 7.137s (min: 7.137s, max: 7.137s)
- snapshots: avg 0.018s (min: 0.018s, max: 0.018s)
- storagedriver_id: avg 0.000s (min: 0.000s, max: 0.000s)
- storagerouter_guid: avg 0.003s (min: 0.003s, max: 0.003s)
- is_vtemplate: avg 0.000s (min: 0.000s, max: 0.000s)
Took 7.198s for 1 iterations
Avg: 7.197s, min: 7.197s, max: 7.197s
```

Snippet to detect such a "slow" call below. You can just wait and the last info it prints is about the disk that takes more than 5 seconds, and if you `CTRL+C` while it seems to hang, you'll get the stacktrace pointing to `...storagedriver_client.statistics_volume`.

```
%cpaste
import time
from ovs.dal.lists.vdisklist import VDiskList
def test():
    try:
        issue_disks = []
        while True:
            for d in VDiskList.get_vdisks():
                print '{0}: {1}'.format(d.volume_id, d.name)
                s = time.time()
                d._benchmark(1)
                elapsed = time.time() - s
                if elapsed > 0.25:
                    issue_disks.append('{0}: {1} - {2}'.format(d.volume_id, d.name, elapsed))
                if elapsed > 5:
                    raise RuntimeError()
            time.sleep(1)
    except:
        for l in issue_disks:
            print l
        raise
--
```

**Comment by wimpers** [comment] 2016-07-27 08:29
Do note that the call hangs on disks which aren't moved.

**Comment by redlicha** [comment] 2016-08-31 19:28
Possibly related to #101

**Comment by wimpers** [comment] 2017-05-30 13:12
@JeffreyDevloo @pploegaert can you please verify if this is still an open issue?

**Comment by JeffreyDevloo** [comment] 2018-01-09 15:40
As far as I know, this is no longer an issue
During moves, the management call resolves quite fast so I suppose this can be closed down

**Comment by JeffreyDevloo** [comment] 2018-01-09 16:10
Moving a single volume did not impact it at all:
```
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.003s (min: 0.003s, max: 0.003s)
- edge_clients: avg 0.015s (min: 0.015s, max: 0.015s)
- statistics: avg 0.008s (min: 0.008s, max: 0.008s)
- snapshot_ids: avg 0.002s (min: 0.002s, max: 0.002s)
- snapshots: avg 0.284s (min: 0.284s, max: 0.284s)
- dtl_status: avg 0.039s (min: 0.039s, max: 0.039s)
- storagerouter_guid: avg 0.007s (min: 0.007s, max: 0.007s)
- is_vtemplate: avg 0.011s (min: 0.011s, max: 0.011s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.369s for 1 iterations
Avg: 0.369s, min: 0.369s, max: 0.369s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.002s (min: 0.002s, max: 0.002s)
- edge_clients: avg 0.003s (min: 0.003s, max: 0.003s)
- statistics: avg 0.003s (min: 0.003s, max: 0.003s)
- snapshot_ids: avg 0.002s (min: 0.002s, max: 0.002s)
- snapshots: avg 0.004s (min: 0.004s, max: 0.004s)
- dtl_status: avg 0.042s (min: 0.042s, max: 0.042s)
- storagerouter_guid: avg 0.002s (min: 0.002s, max: 0.002s)
- is_vtemplate: avg 0.002s (min: 0.002s, max: 0.002s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.062s for 1 iterations
Avg: 0.062s, min: 0.062s, max: 0.062s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.003s (min: 0.003s, max: 0.003s)
- edge_clients: avg 0.004s (min: 0.004s, max: 0.004s)
- statistics: avg 0.004s (min: 0.004s, max: 0.004s)
- snapshot_ids: avg 0.006s (min: 0.006s, max: 0.006s)
- snapshots: avg 0.007s (min: 0.007s, max: 0.007s)
- dtl_status: avg 0.080s (min: 0.080s, max: 0.080s)
- storagerouter_guid: avg 0.006s (min: 0.006s, max: 0.006s)
- is_vtemplate: avg 0.004s (min: 0.004s, max: 0.004s)
- storagedriver_id: avg 0.006s (min: 0.006s, max: 0.006s)
Took 0.118s for 1 iterations
Avg: 0.118s, min: 0.118s, max: 0.118s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.003s (min: 0.003s, max: 0.003s)
- edge_clients: avg 0.003s (min: 0.003s, max: 0.003s)
- statistics: avg 0.005s (min: 0.005s, max: 0.005s)
- snapshot_ids: avg 0.003s (min: 0.003s, max: 0.003s)
- snapshots: avg 0.003s (min: 0.003s, max: 0.003s)
- dtl_status: avg 0.031s (min: 0.031s, max: 0.031s)
- storagerouter_guid: avg 0.003s (min: 0.003s, max: 0.003s)
- is_vtemplate: avg 0.002s (min: 0.002s, max: 0.002s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.054s for 1 iterations
Avg: 0.054s, min: 0.054s, max: 0.054s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.003s (min: 0.003s, max: 0.003s)
- edge_clients: avg 0.004s (min: 0.004s, max: 0.004s)
- statistics: avg 0.004s (min: 0.004s, max: 0.004s)
- snapshot_ids: avg 0.002s (min: 0.002s, max: 0.002s)
- snapshots: avg 0.003s (min: 0.003s, max: 0.003s)
- dtl_status: avg 0.036s (min: 0.036s, max: 0.036s)
- storagerouter_guid: avg 0.003s (min: 0.003s, max: 0.003s)
- is_vtemplate: avg 0.002s (min: 0.002s, max: 0.002s)
- storagedriver_id: avg 0.002s (min: 0.002s, max: 0.002s)
Took 0.059s for 1 iterations
Avg: 0.059s, min: 0.059s, max: 0.059s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.004s (min: 0.004s, max: 0.004s)
- edge_clients: avg 0.003s (min: 0.003s, max: 0.003s)
- statistics: avg 0.005s (min: 0.005s, max: 0.005s)
- snapshot_ids: avg 0.006s (min: 0.006s, max: 0.006s)
- snapshots: avg 0.012s (min: 0.012s, max: 0.012s)
- dtl_status: avg 0.067s (min: 0.067s, max: 0.067s)
- storagerouter_guid: avg 0.003s (min: 0.003s, max: 0.003s)
- is_vtemplate: avg 0.003s (min: 0.003s, max: 0.003s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.104s for 1 iterations
Avg: 0.104s, min: 0.104s, max: 0.104s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.002s (min: 0.002s, max: 0.002s)
- edge_clients: avg 0.004s (min: 0.004s, max: 0.004s)
- statistics: avg 0.004s (min: 0.004s, max: 0.004s)
- snapshot_ids: avg 0.002s (min: 0.002s, max: 0.002s)
- snapshots: avg 0.004s (min: 0.004s, max: 0.004s)
- dtl_status: avg 0.045s (min: 0.045s, max: 0.045s)
- storagerouter_guid: avg 0.005s (min: 0.005s, max: 0.005s)
- is_vtemplate: avg 0.003s (min: 0.003s, max: 0.003s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.071s for 1 iterations
Avg: 0.071s, min: 0.071s, max: 0.071s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.003s (min: 0.003s, max: 0.003s)
- edge_clients: avg 0.004s (min: 0.004s, max: 0.004s)
- statistics: avg 0.004s (min: 0.004s, max: 0.004s)
- snapshot_ids: avg 0.004s (min: 0.004s, max: 0.004s)
- snapshots: avg 0.004s (min: 0.004s, max: 0.004s)
- dtl_status: avg 0.052s (min: 0.052s, max: 0.052s)
- storagerouter_guid: avg 0.014s (min: 0.014s, max: 0.014s)
- is_vtemplate: avg 0.003s (min: 0.003s, max: 0.003s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.089s for 1 iterations
Avg: 0.088s, min: 0.088s, max: 0.088s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.001s (min: 0.001s, max: 0.001s)
- edge_clients: avg 0.004s (min: 0.004s, max: 0.004s)
- statistics: avg 0.002s (min: 0.002s, max: 0.002s)
- snapshot_ids: avg 0.001s (min: 0.001s, max: 0.001s)
- snapshots: avg 0.003s (min: 0.003s, max: 0.003s)
- dtl_status: avg 0.032s (min: 0.032s, max: 0.032s)
- storagerouter_guid: avg 0.003s (min: 0.003s, max: 0.003s)
- is_vtemplate: avg 0.003s (min: 0.003s, max: 0.003s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.049s for 1 iterations
Avg: 0.049s, min: 0.049s, max: 0.049s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.003s (min: 0.003s, max: 0.003s)
- edge_clients: avg 0.006s (min: 0.006s, max: 0.006s)
- statistics: avg 0.005s (min: 0.005s, max: 0.005s)
- snapshot_ids: avg 0.002s (min: 0.002s, max: 0.002s)
- snapshots: avg 0.003s (min: 0.003s, max: 0.003s)
- dtl_status: avg 0.046s (min: 0.046s, max: 0.046s)
- storagerouter_guid: avg 0.004s (min: 0.004s, max: 0.004s)
- is_vtemplate: avg 0.003s (min: 0.003s, max: 0.003s)
- storagedriver_id: avg 0.002s (min: 0.002s, max: 0.002s)
Took 0.073s for 1 iterations
Avg: 0.073s, min: 0.073s, max: 0.073s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.001s (min: 0.001s, max: 0.001s)
- edge_clients: avg 0.005s (min: 0.005s, max: 0.005s)
- statistics: avg 0.002s (min: 0.002s, max: 0.002s)
- snapshot_ids: avg 0.001s (min: 0.001s, max: 0.001s)
- snapshots: avg 0.002s (min: 0.002s, max: 0.002s)
- dtl_status: avg 0.032s (min: 0.032s, max: 0.032s)
- storagerouter_guid: avg 0.004s (min: 0.004s, max: 0.004s)
- is_vtemplate: avg 0.002s (min: 0.002s, max: 0.002s)
- storagedriver_id: avg 0.003s (min: 0.003s, max: 0.003s)
Took 0.053s for 1 iterations
Avg: 0.053s, min: 0.053s, max: 0.053s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.001s (min: 0.001s, max: 0.001s)
- edge_clients: avg 0.003s (min: 0.003s, max: 0.003s)
- statistics: avg 0.002s (min: 0.002s, max: 0.002s)
- snapshot_ids: avg 0.001s (min: 0.001s, max: 0.001s)
- snapshots: avg 0.001s (min: 0.001s, max: 0.001s)
- dtl_status: avg 0.026s (min: 0.026s, max: 0.026s)
- storagerouter_guid: avg 0.002s (min: 0.002s, max: 0.002s)
- is_vtemplate: avg 0.002s (min: 0.002s, max: 0.002s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.040s for 1 iterations
Avg: 0.040s, min: 0.040s, max: 0.040s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.002s (min: 0.002s, max: 0.002s)
- edge_clients: avg 0.003s (min: 0.003s, max: 0.003s)
- statistics: avg 0.004s (min: 0.004s, max: 0.004s)
- snapshot_ids: avg 0.001s (min: 0.001s, max: 0.001s)
- snapshots: avg 0.003s (min: 0.003s, max: 0.003s)
- dtl_status: avg 0.052s (min: 0.052s, max: 0.052s)
- storagerouter_guid: avg 0.003s (min: 0.003s, max: 0.003s)
- is_vtemplate: avg 0.002s (min: 0.002s, max: 0.002s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.072s for 1 iterations
Avg: 0.072s, min: 0.072s, max: 0.072s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.002s (min: 0.002s, max: 0.002s)
- edge_clients: avg 0.004s (min: 0.004s, max: 0.004s)
- statistics: avg 0.004s (min: 0.004s, max: 0.004s)
- snapshot_ids: avg 0.003s (min: 0.003s, max: 0.003s)
- snapshots: avg 0.004s (min: 0.004s, max: 0.004s)
- dtl_status: avg 0.039s (min: 0.039s, max: 0.039s)
- storagerouter_guid: avg 0.003s (min: 0.003s, max: 0.003s)
- is_vtemplate: avg 0.004s (min: 0.004s, max: 0.004s)
- storagedriver_id: avg 0.002s (min: 0.002s, max: 0.002s)
Took 0.065s for 1 iterations
Avg: 0.065s, min: 0.065s, max: 0.065s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.002s (min: 0.002s, max: 0.002s)
- edge_clients: avg 0.004s (min: 0.004s, max: 0.004s)
- statistics: avg 0.002s (min: 0.002s, max: 0.002s)
- snapshot_ids: avg 0.001s (min: 0.001s, max: 0.001s)
- snapshots: avg 0.001s (min: 0.001s, max: 0.001s)
- dtl_status: avg 0.068s (min: 0.068s, max: 0.068s)
- storagerouter_guid: avg 0.002s (min: 0.002s, max: 0.002s)
- is_vtemplate: avg 0.003s (min: 0.003s, max: 0.003s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.085s for 1 iterations
Avg: 0.085s, min: 0.085s, max: 0.085s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.002s (min: 0.002s, max: 0.002s)
- edge_clients: avg 0.005s (min: 0.005s, max: 0.005s)
- statistics: avg 0.003s (min: 0.003s, max: 0.003s)
- snapshot_ids: avg 0.001s (min: 0.001s, max: 0.001s)
- snapshots: avg 0.003s (min: 0.003s, max: 0.003s)
- dtl_status: avg 0.034s (min: 0.034s, max: 0.034s)
- storagerouter_guid: avg 0.004s (min: 0.004s, max: 0.004s)
- is_vtemplate: avg 0.003s (min: 0.003s, max: 0.003s)
- storagedriver_id: avg 0.002s (min: 0.002s, max: 0.002s)
Took 0.055s for 1 iterations
Avg: 0.055s, min: 0.055s, max: 0.055s
ccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg
Object: VDisk('0fe59f1c-88a9-4c81-a9fe-8455b7e558ac')
- info: avg 0.001s (min: 0.001s, max: 0.001s)
- edge_clients: avg 0.004s (min: 0.004s, max: 0.004s)
- statistics: avg 0.002s (min: 0.002s, max: 0.002s)
- snapshot_ids: avg 0.001s (min: 0.001s, max: 0.001s)
- snapshots: avg 0.002s (min: 0.002s, max: 0.002s)
- dtl_status: avg 0.036s (min: 0.036s, max: 0.036s)
- storagerouter_guid: avg 0.004s (min: 0.004s, max: 0.004s)
- is_vtemplate: avg 0.003s (min: 0.003s, max: 0.003s)
- storagedriver_id: avg 0.001s (min: 0.001s, max: 0.001s)
Took 0.054s for 1 iterations
Avg: 0.054s, min: 0.054s, max: 0.054s
^Cccd22f1d-07a5-4690-8a0e-07cfbd460d8a: egwwg - 0.369251012802

```

**Comment by wimpers** [comment] 2018-01-09 16:13
See test above. hence closing down with can't reproduce.

**Closed by wimpers** 2018-01-09 16:13 UTC
Labels: priority_urgent, process_cantreproduce, type_bug
