### ISSUE TITLE
live migrate has non-deterministic outcome

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/volumedriver#198] opened 2016-12-08 13:47 UTC
As observed on OVH demo environment

Scenario: vm running fio, migrate to another location

Observed outcome: intermittent failure/success

VM had read-only fs, it got an IO error and for some reason HA kicked in

Potential issue: race between threshold on voldrv side and edge following, as suggested by @redlicha: the threshold on voldrv side could be set to 0, but this might not be what we want in this kind of demo?
So when it works it is by chance and not by design, the edge client checks the location periodically and will connect to the current voldrv ...

This needs to be investigated further as suggested to be able to give a proper demo of this feature
Might be related to a restarted proxy on the OVH environment, which could have triggered HA ...

**Comment by redlicha** [comment] 2016-12-08 14:47
Observation:
13:10:22: successful auto-migration of V from R1 -> G5
13:12:31: R1 steals V due to a request timeout, fencing kicks in on G5

* DTL is configured to be in asynchronous mode (= volume stealing should only be possible under certain conditions)
* V was choking on G5 around the time of the timeout

**Comment by redlicha** [comment] 2016-12-08 15:07
Related: #139

**Comment by redlicha** [comment] 2016-12-12 08:02
In that particular case, the race of auto-migration vs. client reconnecting to the location was not coming into play, but rather a trigger happy HA stealing the volume.

**Comment by wimpers** [comment] 2016-12-12 13:17
Duplicate of https://github.com/openvstorage/volumedriver/issues/139

**Closed** 2016-12-12 13:17 UTC
Labels: priority_critical, process_duplicate
