### ISSUE TITLE
UpdateMetaDataBackendConfig call should release the mgmt lock

### ISSUE THREAD

**Issue by redlicha** [openvstorage/volumedriver#373] opened 2017-12-19 17:29 UTC
This call might take long (which should be addressed as well - is #339 sufficient?), locking out other mgmt calls.

**Comment by wimpers** [comment] 2018-04-27 08:32
Duplicate of https://github.com/openvstorage/volumedriver-ee/issues/34

**Closed as completed** 2018-04-27 08:32 UTC
Labels: type_bug, process_duplicate
