### ISSUE TITLE
Volumedriver gives up quickly when trying to mount a volume if it can't write owner_tag to the backend

### ISSUE THREAD

**Issue by domsj** [openvstorage/volumedriver#246] opened 2017-01-27 13:57 UTC
This was seen in https://github.com/openvstorage/volumedriver/issues/244.
A possible enhancement would be for the volumedriver to try a bit harder/longer.
More retries, combined with an exponential backoff (such as the strategy for writing scos/tlogs) might be a good idea here.

Fyi: related to the issue seen there an alba issue (possible enhancement) was created too https://github.com/openvstorage/alba/issues/596.

**Comment by wimpers** [comment] 2017-02-13 12:50
@redlicha is this a big one?

**Comment by wimpers** [comment] 2017-02-13 12:51
After a while this gets fixed (f.e. during auto update)

**Comment by redlicha** [comment] 2017-03-07 09:40
The retry behaviour for this is currently governed by the backend config passed to volumedriver. In the linked case there was only one retry which was very probably caused by the framework passing in a backend config that had the relevant keys in the wrong config section, which should however be fixed now so that the same retry rules apply as for reads:
```
"backend_interface_retries_on_error": 5,
"backend_interface_retry_backoff_multiplier": 2.0,
"backend_interface_retry_interval_secs": 1,
```
(which are different from the ones used for SCO / TLog uploads - these are retried basically infinitely).

**Comment by redlicha** [comment] 2017-03-07 09:40
Related: #222

**Comment by redlicha** [comment] 2017-05-11 08:56
Closing for now. Please reopen if the current retry behaviour is not good enough.

**Closed by redlicha** 2017-05-11 08:56 UTC
Labels: state_verification, type_enhancement
