### ISSUE TITLE
HA split brain?

### ISSUE THREAD

**Issue by dejonghb** [openvstorage/volumedriver#274] opened 2017-02-23 15:17 UTC
- start a VM from existing vdisk
```
kvm -drive file=openvstorage+tcp:172.22.186.32:26221/yavm,if=virtio,cache=none,format=raw -net nic -net user -m 2048 -vnc :0 -redir tcp:2222::22
```
![fa_be4](https://cloud.githubusercontent.com/assets/15377625/23264943/61701012-f9e3-11e6-8dc3-bbe27b188ff4.png)
- on the owner storagerouter trigger HA using iptables to DROP all traffic on the vpool the vdisk lives 
```
iptables -A INPUT -p tcp --dport 26218:26221 -j DROP
```
- HA succeeds; ownership of volume is moved to other node
![fa_ftcmp03](https://cloud.githubusercontent.com/assets/15377625/23264976/7a7ad790-f9e3-11e6-93bb-bf4c1f814632.png)

- flush iptables & shutdown VM
- restart VM 

Result: edge connection to original storagerouter, not moved to new owner 
(sometimes VM starts; other times a VM panic results -- qemu remains running)
![fa_wrong](https://cloud.githubusercontent.com/assets/15377625/23264982/8379e188-f9e3-11e6-810b-b696c2c825b0.png)

Note: shutdown of VM after stealing is very slow

**Comment by dejonghb** [comment] 2017-02-23 15:23
![fsck_required](https://cloud.githubusercontent.com/assets/15377625/23265252/633eb17c-f9e4-11e6-8ffc-aba33d019556.png)

**Comment by dejonghb** [comment] 2017-02-23 15:46
```
Feb 23 16:08:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:08:02 599316 +0100 - ftcmp0 - 1983/0x00007fd56e685c00 - logger/libovsvolumedriver - 0000000000000000 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - NetworkHAContext(81): uri: tcp://172.22.186.32:26221,queue depth: 64
Feb 23 16:08:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:08:02 599649 +0100 - ftcmp0 - 1983/0x00007fd56e685c00 - logger/libovsvolumedriver - 0000000000000001 - info - libovsvolumedriver::NetworkXioClient(0x562fb03296c0) - NetworkXioClient(140): uri: tcp://172.22.186.32:26221, queue depth: 64
Feb 23 16:08:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:08:02 610126 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000002 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:08:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:08:02 613864 +0100 - ftcmp0 - 1983/0x00007fd56e685c00 - logger/libovsvolumedriver - 0000000000000003 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(382): cluster node URIs for yavm:
Feb 23 16:08:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:08:02 613904 +0100 - ftcmp0 - 1983/0x00007fd56e685c00 - logger/libovsvolumedriver - 0000000000000004 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.34:26215
Feb 23 16:08:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:08:02 613917 +0100 - ftcmp0 - 1983/0x00007fd56e685c00 - logger/libovsvolumedriver - 0000000000000005 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.33:26215
Feb 23 16:08:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:08:02 622977 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000006 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(382): cluster node URIs for yavm:
Feb 23 16:08:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:08:02 623034 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000007 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.34:26215
Feb 23 16:08:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:08:02 623048 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000008 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.33:26215
Feb 23 16:08:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:08:32 620392 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000009 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:09:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:09:02 630857 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000000a - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:09:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:09:32 639215 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000000b - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:10:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:10:02 648424 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000000c - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:10:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:10:32 658024 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000000d - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:11:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:11:02 666316 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000000e - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:11:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:11:32 673415 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000000f - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:12:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:12:02 682594 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000010 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:12:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:12:32 691524 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000011 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:13:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:13:02 635191 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000012 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(382): cluster node URIs for yavm:
Feb 23 16:13:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:13:02 635254 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000013 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.33:26215
Feb 23 16:13:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:13:02 635283 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000014 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.34:26215
Feb 23 16:13:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:13:02 701157 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000015 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:13:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:13:32 708840 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000016 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:14:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:14:02 721948 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000017 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:14:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:14:32 734153 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000018 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:15:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:15:02 742701 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000019 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:15:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:15:32 754659 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000001a - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:16:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:16:02 763626 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000001b - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:16:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:16:32 772234 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000001c - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:17:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:17:02 782618 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000001d - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:17:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:17:32 793335 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000001e - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:18:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:18:02 643545 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000001f - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(382): cluster node URIs for yavm:
Feb 23 16:18:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:18:02 643607 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000020 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.33:26215
Feb 23 16:18:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:18:02 643635 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000021 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.34:26215
Feb 23 16:18:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:18:02 800650 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000022 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:18:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:18:32 809560 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000023 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:19:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:19:02 819716 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000024 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:19:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:19:32 830058 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000025 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:20:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:20:02 838744 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000026 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:20:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:20:32 846904 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000027 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:21:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:21:02 855098 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000028 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:21:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:21:32 866019 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000029 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:22:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:22:02 878824 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000002a - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:22:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:22:32 886912 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000002b - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:23:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:23:02 653710 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000002c - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(382): cluster node URIs for yavm:
Feb 23 16:23:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:23:02 653774 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000002d - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.34:26215
Feb 23 16:23:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:23:02 653801 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000002e - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.33:26215
Feb 23 16:23:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:23:02 896436 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000002f - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:23:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:23:32 905808 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000030 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:24:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:24:02 913246 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000031 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:24:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:24:32 924290 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000032 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:25:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:25:02 933438 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000033 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:25:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:25:32 940986 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000034 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:26:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:26:02 950746 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000035 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:26:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:26:32 963177 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000036 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:27:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:27:02 972460 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000037 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:27:32 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:27:32 983577 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000038 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:28:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:28:02 664869 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000039 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(382): cluster node URIs for yavm:
Feb 23 16:28:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:28:02 664944 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000003a - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.33:26215
Feb 23 16:28:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:28:02 664971 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000003b - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - update_cluster_node_uri(385):         tcp://172.22.186.34:26215
Feb 23 16:28:02 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:28:02 994045 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000003c - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:28:33 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:28:33 002438 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000003d - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:29:03 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:29:03 010519 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000003e - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:29:33 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:29:33 019992 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 000000000000003f - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:30:03 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:30:03 028377 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000040 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:30:33 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:30:33 038495 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000041 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:31:03 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:31:03 050287 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000042 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
Feb 23 16:31:33 ftcmp0 qemu-system-x86_64[1983]: 2017-02-23 16:31:33 060921 +0100 - ftcmp0 - 1983/0x00007fd547927700 - logger/libovsvolumedriver - 0000000000000043 - info - libovsvolumedriver::NetworkHAContext(0x562fb0327860) - maybe_update_volume_location(398): yavm: check if location has changed
```

**Comment by redlicha** [comment] 2017-02-27 08:16
Caused by the location check using / returning the cached location info.

**Comment by redlicha** [comment] 2017-03-01 13:52
To clarify: this is not a split brain as fencing prevents writing to / reading from the old instance.

**Comment by redlicha** [comment] 2017-03-08 08:52
TBD: address the race mentioned above.

**Comment by wimpers** [comment] 2017-08-29 09:33
Closed by PM.

**Closed by wimpers** 2017-08-29 09:33 UTC
Labels: state_verification, type_bug
