### ISSUE TITLE
Vpool not mount after some days

### ISSUE THREAD

**Issue by hoanhdo** [openvstorage/volumedriver#275] opened 2017-02-24 08:51 UTC
HI all.
I create a cluster on openvstorage fargo.
after some days i don't work with openvstorage, vpool not mount.
But process vpool still work.
Thanks.
Hoan

**Comment by jeroenmaelbrancke** [comment] 2017-02-27 08:37
Hi Hoan,

Is it possible to send us the volumedriver log files?

regards,
Jeroen M

**Comment by wimpers** [comment] 2017-03-03 14:49
hi @hoanhdo, 

 any update about the logs? Is the issue solved?

Kind regards,
Wim Provoost
Product Manager Open vStorage

**Comment by hoanhdo** [comment] 2017-03-07 02:20
Sorry, i am busy.
This is my log file 
[log_volumedriver.txt](https://github.com/openvstorage/volumedriver/files/823174/log_volumedriver.txt)
Thanks.

**Comment by hoanhdo** [comment] 2017-03-07 08:07
Yes. This is my log
[test.txt](https://github.com/openvstorage/volumedriver/files/823726/test.txt)
Thanks

**Comment by jeroenmaelbrancke** [comment] 2017-03-07 08:56
What is the output from cat /proc/mounts and df -h?
The command i provided you should give me all the logging from the volumedriver but i only see 2 hours.
How is your journalctl configured (cat /etc/systemd/journald.conf)?

Regards,
Jeroen M

**Comment by hoanhdo** [comment] 2017-03-07 09:43
I just start machine. 
This is my disk info.
[disk.txt](https://github.com/openvstorage/volumedriver/files/823945/disk.txt)

**Comment by jeroenmaelbrancke** [comment] 2017-03-07 10:06
@hoanhdo 

Can you go to the ovs gui --> Administration --> Support --> Remote access enabled = true --> Save settings.

Can you send me the root credentials + cluster id ( section Support information) to jeroen.maelbrancke@openvstorage.com?

i'll try to login on your environment and have a look.

Regards,
Jeroen M

**Comment by jeroenmaelbrancke** [comment] 2017-03-08 12:24
Hi @hoanhdo,

After taking a look at your environment we would like to install gdb and the matching debug symbols.
Is this okay for you?

We see in the volumedriver that restarting a volume hangs but we do not know where, that's why we would like to install the gdb and debug symbols.

Journalctl also skipped some messages from the volumedriver but we found the logs in /var/log/syslog.
That is why the logging you sent earlier was only for 2 hours.

In the logging we saw that some processes from the volumedriver stopped logging. Gdb would help us here why those processes are hanging.

A second concern are the disks.
This server is a virtual machine on VMware and we see some performance issues on some disk especially sda .

```
root@openvstorage:~# hdparm -tT /dev/sdb

/dev/sdb:
 Timing cached reads:   17934 MB in  2.00 seconds = 8971.98 MB/sec
 Timing buffered disk reads: 1646 MB in  3.00 seconds = 548.24 MB/sec
root@openvstorage:~# hdparm -tT /dev/sdc

/dev/sdc:
 Timing cached reads:   15730 MB in  2.00 seconds = 7869.87 MB/sec
 Timing buffered disk reads: 1156 MB in  3.00 seconds = 385.24 MB/sec
root@openvstorage:~# hdparm -tT /dev/sdd

/dev/sdd:
 Timing cached reads:   14976 MB in  2.00 seconds = 7491.70 MB/sec
 Timing buffered disk reads: 3992 MB in  3.00 seconds = 1329.50 MB/sec
root@openvstorage:~# hdparm -tT /dev/sde

/dev/sde:
 Timing cached reads:   14682 MB in  2.00 seconds = 7345.97 MB/sec
 Timing buffered disk reads: 4832 MB in  3.00 seconds = 1610.22 MB/sec
root@openvstorage:~# hdparm -tT /dev/sda

/dev/sda:
 Timing cached reads:   13536 MB in  2.00 seconds = 6770.91 MB/sec
 Timing buffered disk reads: 250 MB in  3.04 seconds =  82.26 MB/sec
```

Before doing anything on the second concern can you please give us a go to install the necessarily packages? 

Kind regards,
Jeroen M

**Comment by hoanhdo** [comment] 2017-03-09 03:49
Hi jeroenmaelbrancke.
What package i need install : gdb, volumedriver-no-dedup-base-dbgsym and volumedriver-no-dedup-server-dbgsym?

**Comment by jeroenmaelbrancke** [comment] 2017-03-09 09:36
Is it okay that we install the package?

**Comment by hoanhdo** [comment] 2017-03-10 01:49
I installed these packages. you do .

**Comment by jeroenmaelbrancke** [comment] 2017-03-10 09:18
@redlicha 
[voldrv-hang-evidence.tar.gz](https://github.com/openvstorage/volumedriver/files/833429/voldrv-hang-evidence.tar.gz)

**Comment by jeroenmaelbrancke** [comment] 2017-04-07 06:58
@redlicha 
If you have some time please do not forget to check the coredumps of this ticket.

**Comment by redlicha** [comment] 2017-08-28 14:14
Inspection of the gdb log / core dump shows  a number of threads waiting for a condition variable internal to RocksDB (one of the threads being the main thread trying to restart a volume). At the same time the expected internal RocksDB threads (`rocksdb:bgX`) are *not* present - reason is unclear and the attached volumedriver logindicates dropped (rate-limited?) messages (seq num jumps from 0x301 to 0x4b1):
```
Mar 07 09:17:06 openvstorage volumedriver_fs.sh[2362]: 2017-03-07 09:17:05 907224 +0700 - openvstorage - 2362/0x00007f0b61ed7900 - volumedriverfs/RocksLogger - 0000000000000301 - info - /mnt/hdd1/vpooldemo_db_mds_1:              Options.max_background_compactions: 0
Mar 07 09:17:38 openvstorage volumedriver_fs.sh[2362]: 2017-03-07 09:17:38 799546 +0700 - openvstorage - 2362/0x00007f0b3affd700 - volumedriverfs/MetaDataServerTable - 00000000000004b1 - info - work_: 2e6e5d69-acc8-4939-8332-d2b6de9f4a27: running periodic action
```

@wimpers : since this was never reproduced / has never been reported again, I suggest to close this ticket as "not reproducible" and to reopen it if necessary.

**Comment by wimpers** [comment] 2017-08-28 14:17
See comment from @redlicha , please re-open if we can reproduce or if we have more evidence.

**Closed by wimpers** 2017-08-28 14:17 UTC
Labels: process_cantreproduce
