### ISSUE TITLE
Volume does not exist not handled correctly

### ISSUE THREAD

**Issue by saelbrec** [openvstorage/volumedriver#133] opened 2016-09-30 15:39 UTC
Testing manual HA earlier this week I experienced the following issue.
After shutting down a node and having it marked offline the other node failed to steal a certain volume. Then the initial node and volumedriver owner were started again, after which a client tried to access to volume via the initial owner, at that point the volumedriver died with the below unhandled exception.

```
2016-09-27 22:27:13 714495 +0200 - stor-202.be-gen8-1 - 3456/0x00007fc4f57fa700 - volumedriverfs/VFSObjectRouter - 0000000000000425 - error - do_route_: 91669211-1bc8-43e8-9dd0-dea67a8e1113: volume location not found, giving up
terminate called after throwing an instance of 'volumedriver::VolManager::VolumeDoesNotExistException'
  what():  Volume location not found 91669211-1bc8-43e8-9dd0-dea67a8e1113
Tue Sep 27 22:27:25 CEST 2016 [30569]: No officially blessed alternative allocator found, using libc's allocator
```

**Comment by redlicha** [comment] 2016-10-10 07:41
Duplicate of #100 : an exception was not handled in a thread which eventually leads to `terminate` being invoked.

**Closed by redlicha** 2016-10-10 07:41 UTC
