### ISSUE TITLE
qemu-img: output file is smaller than input file

### ISSUE THREAD

**Issue by hoanhdo** [openvstorage/volumedriver#330] opened 2017-07-19 08:10 UTC
Hi all.

I use qemu-img convert to create vdisk from image. My image size 275MB, vdisk has size : 1.34GB.
This is my qemu command.

> env LC_ALL=C LANG=C qemu-img convert -n -O raw /tmp/3d83da3c-9dcb-4d67-8858-6dd311d10016 openvstorage+tcp:10.5.8.27:26209/glance-3d83da3c-9dcb-4d67-8858-6dd311d10016

file size 
> -rw-r----- 1 glance glance 275M Jul 19 15:07 /tmp/3d83da3c-9dcb-4d67-8858-6dd311d10016

error

> Stderr: u'qemu-img: output file is smaller than input file\n'

Thanks.

**Comment by wimpers** [comment] 2017-08-18 13:06
@hoanhdo

I'm wondering if the issue is that the image virtual size is larger than then volume size.

Can you execute for the vdi `qemu-img info` and check the virtual size? In that case as workaroudn create a volume with a size bigger than the virtual size of the image.

**Comment by hoanhdo** [comment] 2017-08-19 02:41
@wimpers 
Thanks. I will try.

**Comment by wimpers** [comment] 2017-09-08 07:25
@hoanhdo,

I will close this one down. Re-open in case the issue isn't fixed by the above suggestion.

**Closed by wimpers** 2017-09-08 07:25 UTC
Labels: state_question
