### ISSUE TITLE
Quickly removing and recreating a volume with the same name triggers a fault

### ISSUE THREAD

**Issue by FastGeert** [openvstorage/volumedriver#110] opened 2016-09-09 09:06 UTC
Disks of routeros virtual machines in OVC are being created with a specific naming convention. It happens that these routeros virtual machines are quickly recycled, and this triggers a race condition in the volumedriver.

The result is that the "recreated" volume is left in a zombie state, that can only be solved by expert ops to clean it up.

**Comment by redlicha** [comment] 2016-09-09 10:26
Can you please provide more details on how this recycling takes place, i.e. how are volumes created and removed and which nodes are involved (specifically I'm wondering if this is a duplicate of #71 ?)

**Comment by despiegk** [comment] 2016-09-09 10:41
the fuse way is used to create/delete the volumes 
maybe the workaround is to use the rest api

**Comment by wimpers** [comment] 2016-09-14 13:13
@FastGeert is this still the case after changing the implementation to use the REST API

**Comment by FastGeert** [comment] 2016-09-14 13:53
Can't say yet. We need to do more testing.

**Comment by wimpers** [comment] 2016-09-26 09:50
@FastGeert any update on this ticket? Can we close this ticket?

**Comment by wimpers** [comment] 2016-10-03 09:30
After discussion with @FastGeert set to closed as using the REST API doesn't trick the behaviour.

**Closed** 2016-10-03 09:30 UTC
Labels: process_wontfix
